### ISSUE TITLE
application tries to access table before migrations are run

### ISSUE THREAD

**Issue by robot-o** [Corridors-of-Time-Transcription/puzzlepieces#5]
```
puzzlepieces_backend | Traceback (most recent call last):
puzzlepieces_backend |   File "manage.py", line 21, in <module>
puzzlepieces_backend |     main()
puzzlepieces_backend |   File "manage.py", line 17, in main
puzzlepieces_backend |     execute_from_command_line(sys.argv)
puzzlepieces_backend |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
puzzlepieces_backend |     utility.execute()
puzzlepieces_backend |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
puzzlepieces_backend |     self.fetch_command(subcommand).run_from_argv(self.argv)
puzzlepieces_backend |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
puzzlepieces_backend |     self.execute(*args, **cmd_options)
puzzlepieces_backend |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
puzzlepieces_backend |     output = self.handle(*args, **options)
puzzlepieces_backend |   File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/flush.py", line 47, in handle
puzzlepieces_backend |     sql_list = sql_flush(self.style, connection, only_django=True,
puzzlepieces_backend |   File "/usr/local/lib/python3.8/site-packages/django/core/management/sql.py", line 16, in sql_flush
puzzlepieces_backend |     seqs = connection.introspection.sequence_list() if reset_sequences else ()
puzzlepieces_backend |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/introspection.py", line 116, in sequence_list
puzzlepieces_backend |     sequence_list.extend(self.get_sequences(cursor, model._meta.db_table, model._meta.local_fields))
puzzlepieces_backend |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/introspection.py", line 105, in get_sequences
puzzlepieces_backend |     for field_info in self.get_table_description(cursor, table_name):
puzzlepieces_backend |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/introspection.py", line 84, in get_table_description
puzzlepieces_backend |     cursor.execute("SELECT * FROM %s LIMIT 1" % self.connection.ops.quote_name(table_name))
puzzlepieces_backend |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 100, in execute
puzzlepieces_backend |     return super().execute(sql, params)
puzzlepieces_backend |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 68, in execute
puzzlepieces_backend |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
puzzlepieces_backend |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
puzzlepieces_backend |     return executor(sql, params, many, context)
puzzlepieces_backend |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
puzzlepieces_backend |     return self.cursor.execute(sql, params)
puzzlepieces_backend |   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
puzzlepieces_backend |     raise dj_exc_value.with_traceback(traceback) from exc_value
puzzlepieces_backend |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
puzzlepieces_backend |     return self.cursor.execute(sql)
puzzlepieces_backend |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 74, in execute
puzzlepieces_backend |     return self.cursor.execute(query, args)
puzzlepieces_backend |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 209, in execute
puzzlepieces_backend |     res = self._query(query)
puzzlepieces_backend |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 315, in _query
puzzlepieces_backend |     db.query(q)
puzzlepieces_backend |   File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 239, in query
puzzlepieces_backend |     _mysql.connection.query(self, query)
puzzlepieces_backend | django.db.utils.ProgrammingError: (1146, "Table 'puzzlepieces.collector_puzzlepiece' doesn't exist")
puzzlepieces_backend | Operations to perform:
puzzlepieces_backend |   Apply all migrations: auth, collector, contenttypes, sessions
puzzlepieces_backend | Running migrations:
puzzlepieces_backend |   Applying contenttypes.0001_initial... OK
puzzlepieces_backend |   Applying contenttypes.0002_remove_content_type_name... OK
puzzlepieces_backend |   Applying auth.0001_initial... OK
puzzlepieces_backend |   Applying auth.0002_alter_permission_name_max_length... OK
puzzlepieces_backend |   Applying auth.0003_alter_user_email_max_length... OK
puzzlepieces_backend |   Applying auth.0004_alter_user_username_opts... OK
puzzlepieces_backend |   Applying auth.0005_alter_user_last_login_null... OK
puzzlepieces_backend |   Applying auth.0006_require_contenttypes_0002... OK
puzzlepieces_backend |   Applying auth.0007_alter_validators_add_error_messages... OK
puzzlepieces_backend |   Applying auth.0008_alter_user_username_max_length... OK
puzzlepieces_backend |   Applying auth.0009_alter_user_last_name_max_length... OK
puzzlepieces_backend |   Applying auth.0010_alter_group_name_max_length... OK
puzzlepieces_backend |   Applying auth.0011_update_proxy_permissions... OK
puzzlepieces_backend |   Applying collector.0001_initial... OK
puzzlepieces_backend |   Applying collector.0002_puzzlepiece_hash... OK
puzzlepieces_backend |   Applying collector.0003_auto_20200115_2305... OK
puzzlepieces_backend |   Applying collector.0004_auto_20200116_0044... OK
puzzlepieces_backend |   Applying collector.0005_auto_20200116_0231... OK
puzzlepieces_backend |   Applying collector.0006_auto_20200116_0343... OK
puzzlepieces_backend |   Applying collector.0007_auto_20200116_0343... OK
puzzlepieces_backend |   Applying collector.0008_transcriptiondata_datahash... OK
puzzlepieces_backend |   Applying collector.0009_transcriptiondata_rawdata... OK
puzzlepieces_backend |   Applying collector.0010_auto_20200116_0452... OK
puzzlepieces_backend |   Applying collector.0011_auto_20200116_0535... OK
puzzlepieces_backend |   Applying collector.0012_auto_20200116_0545... OK
puzzlepieces_backend |   Applying collector.0013_badimage... OK
puzzlepieces_backend |   Applying sessions.0001_initial... OK
puzzlepieces_backend | Watching for file changes with StatReloader
puzzlepieces_backend | Performing system checks...
puzzlepieces_backend | 
puzzlepieces_backend | System check identified no issues (0 silenced).
puzzlepieces_backend | January 18, 2020 - 00:02:50
puzzlepieces_backend | Django version 3.0.2, using settings 'puzzlepieces.settings'
puzzlepieces_backend | Starting development server at http://0.0.0.0:8000/
puzzlepieces_backend | Quit the server with CONTROL-C.
```
is thrown before the actual migrations are run

**Comment by robot-o** [comment]
only happens on initial run because of mysql connector attempting to do introspection of each of the tables that are defined in the data model.

closing.
